/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trainsheffield;

import javax.swing.JFrame;



public class App {
    public String runApp() {
        JFrame frame = new JFrame ("Trains Sheffield");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Login());
        frame.pack();
        frame.setVisible (true);
        return "Running the App!";
    }

    public static void main(String[] args) {
        System.out.println(new App().runApp());
    }
}
